services:
  db:
    container_name: serviya-mysql
    image: mysql:8.0
    ports:
      - "${SPRING_DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${SPRING_DB_PASSWORD_ROOT}
      MYSQL_DATABASE: ${SPRING_DB_NAME}
      MYSQL_USER: ${SPRING_DB_USER}
      MYSQL_PASSWORD: ${SPRING_DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: